"""
Registry of awesome lists to scrape, with section-to-category mappings.
"""

# Each entry: (repo_slug, label, section_to_category_map)
# section_to_category_map: regex pattern on section name -> category
# If a section isn't matched, the categorizer module handles it.

AWESOME_LISTS = [
    (
        "sindresorhus/awesome",
        "meta-awesome",
        {}  # meta list — we just grab the links to other lists
    ),
    (
        "jaywcjlove/awesome-mac",
        "awesome-mac",
        {
            r"(?i)developer.?tool": "Code Editors",
            r"(?i)text.?editor": "Code Editors",
            r"(?i)terminal": "Terminal Emulators",
            r"(?i)command.?line": "CLI Frameworks",
            r"(?i)version.?control|git": "Version Control",
            r"(?i)database": "Databases",
            r"(?i)design|prototyp": "UI/UX Design Tools",
            r"(?i)virtual.?machine": "Virtualization",
            r"(?i)communication|chat|messag": "Communication",
            r"(?i)email": "Email",
            r"(?i)browser": "Browsers",
            r"(?i)download|torrent": "Torrent Clients",
            r"(?i)security|password": "Password Managers",
            r"(?i)proxy|vpn": "VPN",
            r"(?i)cloud.?storage": "Cloud Storage",
            r"(?i)backup": "Backup & Sync",
            r"(?i)note": "Note Taking",
            r"(?i)product": "Project Management",
            r"(?i)video.?edit": "Video Editing",
            r"(?i)audio|music": "Music Production",
            r"(?i)image|photo": "Image Editors",
            r"(?i)screen": "Screen Recording / Streaming",
            r"(?i)file.?manag": "File Managers",
            r"(?i)clipboard": "Clipboard Managers",
            r"(?i)window.?manag": "Window Managers",
            r"(?i)launcher": "Launcher & Productivity Utils",
            r"(?i)media.?play": "Media Players",
            r"(?i)pdf|reader": "PDF Tools",
        }
    ),
    (
        "luong-komorebi/Awesome-Linux-Software",
        "awesome-linux",
        {
            r"(?i)text.?editor|ide|code.?editor": "Code Editors",
            r"(?i)terminal.?emulat": "Terminal Emulators",
            r"(?i)shell": "Shell Environments",
            r"(?i)database": "Databases",
            r"(?i)browser": "Browsers",
            r"(?i)email": "Email",
            r"(?i)chat|messag|communi": "Communication",
            r"(?i)video.?edit": "Video Editing",
            r"(?i)image|photo|graphic": "Image Editors",
            r"(?i)audio|music|sound": "Music Production",
            r"(?i)office|document": "Office Suites",
            r"(?i)note": "Note Taking",
            r"(?i)backup|sync": "Backup & Sync",
            r"(?i)security|password|privacy": "Password Managers",
            r"(?i)game": "Game Engines",
            r"(?i)download|torrent": "Torrent Clients",
            r"(?i)file.?manag": "File Managers",
            r"(?i)desktop.?environment|window.?manager": "Window Managers",
            r"(?i)screen": "Screen Recording / Streaming",
            r"(?i)system.?utilit|system.?monitor": "System Utilities",
            r"(?i)proxy|vpn": "VPN",
            r"(?i)launcher": "Launcher & Productivity Utils",
            r"(?i)media.?play|video.?play": "Media Players",
            r"(?i)3d|cad": "3D & CAD",
        }
    ),
    (
        "awesome-selfhosted/awesome-selfhosted",
        "awesome-selfhosted",
        {
            r"(?i)analytics": "Monitoring & Metrics",
            r"(?i)automation": "Project Management",
            r"(?i)blog|cms|content.?manage": "Content Management Systems",
            r"(?i)bookmark": "Utilities",
            r"(?i)calendar|scheduling": "Calendar & Scheduling",
            r"(?i)communication|chat|messag|social": "Communication",
            r"(?i)conference|video.?call": "Video Conferencing",
            r"(?i)document|wiki|knowledge": "Documentation Tools",
            r"(?i)e-commerce|shop": "CRM & Sales",
            r"(?i)email|smtp": "Email",
            r"(?i)feed.?reader|rss": "RSS Readers",
            r"(?i)file.?shar|file.?transfer": "Backup & Sync",
            r"(?i)git|version.?control": "Version Control",
            r"(?i)groupware|project.?manage": "Project Management",
            r"(?i)learning|e-learn": "Learning Platforms",
            r"(?i)media.?stream|music.?stream": "Media Players",
            r"(?i)monitor|metric|status": "Monitoring & Metrics",
            r"(?i)note.?tak": "Note Taking",
            r"(?i)password|secret": "Password Managers",
            r"(?i)photo|gallery|image": "Photo Management",
            r"(?i)vpn": "VPN",
            r"(?i)proxy|dns|network": "Networking",
            r"(?i)search": "Search Engines",
            r"(?i)ticketing|helpdesk": "Project Management",
            r"(?i)url.?short": "Utilities",
        }
    ),
    (
        "vinta/awesome-python",
        "awesome-python",
        {
            r"(?i)admin|cms": "Content Management Systems",
            r"(?i)async|concurrent": "Async & Concurrency",
            r"(?i)auth": "Auth & Identity",
            r"(?i)build|packag": "Build Tools",
            r"(?i)cach": "Caching",
            r"(?i)cli": "CLI Frameworks",
            r"(?i)code.?analy|static.?analy": "Static Analysis",
            r"(?i)lint": "Linters",
            r"(?i)format": "Formatters",
            r"(?i)compat": "Utilities",
            r"(?i)config": "Configuration",
            r"(?i)crypto": "Encryption & Privacy Tools",
            r"(?i)data.?analy|data.?visual": "Data Analysis",
            r"(?i)data.?valid|serial": "Data Validation & Serialization",
            r"(?i)orm|active.?record|persist": "ORMs",
            r"(?i)driver|connector": "Database Drivers",
            r"(?i)migrat": "Database Migrations",
            r"(?i)database|sql|nosql": "Databases",
            r"(?i)date.?time": "Date & Time",
            r"(?i)debug|profil": "Logging & Diagnostics",
            r"(?i)blockchain|ethereum|web3|solidity": "Blockchain & Web3",
            r"(?i)natural.?lang|nlp": "NLP & Text AI",
            r"(?i)llm|openai|langchain|gpt": "LLM Tools",
            r"(?i)deep.?learn|machine.?learn|neural|core.?ml": "AI/ML Libraries",
            r"(?i)ci.?cd|continuous.?integr|devops|deploy.?pipeline": "CI/CD Tools",
            r"(?i)document|pdf": "PDF Tools",
            r"(?i)download|web.?crawl|scrap": "Web Scraping & Parsing",
            r"(?i)text.?editor|code.?editor|ide": "Code Editors",
            r"(?i)email": "Email",
            r"(?i)environment": "Configuration",
            r"(?i)file|path": "File Managers",
            r"(?i)functional": "Utilities",
            r"(?i)game": "Game Engines",
            r"(?i)geolocation|gis": "Data Analysis",
            r"(?i)gui.?framework|gui.?toolkit|gui.?librar|desktop.?framework": "Desktop App Frameworks",
            r"(?i)html|xml": "Web Scraping & Parsing",
            r"(?i)http.?client|urllib|request": "HTTP Libraries",
            r"(?i)image": "Image Processing",
            r"(?i)job|queue|task|schedul": "Data Pipelines",
            r"(?i)logging": "Logging & Diagnostics",
            r"(?i)text|string|regex": "Text Processing",
            r"(?i)news|rss|feed": "RSS Readers",
            r"(?i)science|math|numer": "Scientific Computing",
            r"(?i)search": "Search Engines",
            r"(?i)security": "Security Scanning",
            r"(?i)shell": "Shell Environments",
            r"(?i)template": "Template Engines",
            r"(?i)test": "Testing Frameworks",
            r"(?i)video|audio|music": "Music Production",
            r"(?i)web.?framework|wsgi|asgi": "Backend Frameworks",
            r"(?i)compress|archiv": "Compression & Archiving",
        }
    ),
    (
        "avelino/awesome-go",
        "awesome-go",
        {
            r"(?i)audio|music|video": "Music Production",
            r"(?i)auth": "Auth & Identity",
            r"(?i)bot|chatbot": "Communication",
            r"(?i)build|makefile": "Build Tools",
            r"(?i)tui|text.?ui|terminal.?ui": "Terminal UI",
            r"(?i)cli|command": "CLI Frameworks",
            r"(?i)config": "Configuration",
            r"(?i)css|html|template": "Template Engines",
            r"(?i)data.?struct|algorithm": "Utilities",
            r"(?i)orm": "ORMs",
            r"(?i)driver|connector": "Database Drivers",
            r"(?i)migrat": "Database Migrations",
            r"(?i)cach|redis|memcache": "Caching",
            r"(?i)database|sql|nosql": "Databases",
            r"(?i)date.?time": "Date & Time",
            r"(?i)ci.?cd|continuous.?integr|devops|deploy.?pipeline": "CI/CD Tools",
            r"(?i)email|smtp": "Email",
            r"(?i)embed|iot": "Embedded & IoT",
            r"(?i)error": "Error Handling",
            r"(?i)file|path": "File Managers",
            r"(?i)game": "Game Engines",
            r"(?i)generat|code.?gen": "Utilities",
            r"(?i)gui.?framework|gui.?toolkit|gui.?librar|desktop.?framework": "Desktop App Frameworks",
            r"(?i)http.?client": "HTTP Libraries",
            r"(?i)image": "Image Processing",
            r"(?i)json|serial|valid": "Data Validation & Serialization",
            r"(?i)logging|log.?manage|logger": "Logging & Diagnostics",
            r"(?i)blockchain|ethereum|web3|solidity": "Blockchain & Web3",
            r"(?i)machine.?learn|ai|neural": "AI/ML Libraries",
            r"(?i)messag|queue|stream": "Data Pipelines",
            r"(?i)micro|grpc": "Backend Frameworks",
            r"(?i)monitor|metric|trace": "Monitoring & Metrics",
            r"(?i)network|tcp|udp": "Networking",
            r"(?i)package.?manag|package.?registry": "Package Managers",
            r"(?i)scraper|crawl": "Web Scraping & Parsing",
            r"(?i)search": "Search Engines",
            r"(?i)security|crypto": "Security Scanning",
            r"(?i)test": "Testing Frameworks",
            r"(?i)text|string|regex": "Text Processing",
            r"(?i)compress|archiv": "Compression & Archiving",
            r"(?i)web.?framework|router|middleware": "Backend Frameworks",
        }
    ),
    (
        "rust-unofficial/awesome-rust",
        "awesome-rust",
        {
            r"(?i)tui|text.?ui|terminal.?ui": "Terminal UI",
            r"(?i)cli|command|terminal": "CLI Frameworks",
            r"(?i)compress|archiv": "Compression & Archiving",
            r"(?i)crypto|security": "Encryption & Privacy Tools",
            r"(?i)orm|persist": "ORMs",
            r"(?i)driver|connector": "Database Drivers",
            r"(?i)migrat": "Database Migrations",
            r"(?i)cach|redis|memcache": "Caching",
            r"(?i)database|sql|nosql": "Databases",
            r"(?i)text.?editor|code.?editor|ide": "Code Editors",
            r"(?i)email": "Email",
            r"(?i)embed|iot": "Embedded & IoT",
            r"(?i)game": "Game Engines",
            r"(?i)gui.?framework|gui.?toolkit|gui.?librar|desktop.?framework": "Desktop App Frameworks",
            r"(?i)http.?client": "HTTP Libraries",
            r"(?i)http|web.?framework": "Backend Frameworks",
            r"(?i)image|graphics": "Image Processing",
            r"(?i)logging|log.?manage|logger": "Logging & Diagnostics",
            r"(?i)blockchain|ethereum|web3|solidity": "Blockchain & Web3",
            r"(?i)machine.?learn|ai": "AI/ML Libraries",
            r"(?i)network|protocol": "Networking",
            r"(?i)operating.?system|os": "Operating Systems",
            r"(?i)science|math": "Scientific Computing",
            r"(?i)serial|json|parse": "Data Validation & Serialization",
            r"(?i)system": "System Utilities",
            r"(?i)template": "Template Engines",
            r"(?i)test": "Testing Frameworks",
            r"(?i)text|string|regex": "Text Processing",
            r"(?i)video|audio": "Music Production",
        }
    ),
    (
        "enaqx/awesome-react",
        "awesome-react",
        {
            r"(?i)component|ui": "Frontend Frameworks",
            r"(?i)form": "Frontend Frameworks",
            r"(?i)router": "Frontend Frameworks",
            r"(?i)state.?manage": "Frontend Frameworks",
            r"(?i)style|css": "Frontend Frameworks",
            r"(?i)table|data.?grid": "Frontend Frameworks",
            r"(?i)test": "Testing Frameworks",
            r"(?i)devtool|dev.?tool": "Code Editors",
            r"(?i)type|graphql": "GraphQL Tools",
        }
    ),
    (
        "sorrycc/awesome-javascript",
        "awesome-javascript",
        {
            r"(?i)anima": "Frontend Frameworks",
            r"(?i)bundler|build|task": "Build Tools",
            r"(?i)chart|visual|graph": "Data Analysis",
            r"(?i)cli|command": "CLI Frameworks",
            r"(?i)date.?time|datetime|date.?util": "Date & Time",
            r"(?i)text.?editor|code.?editor|wysiwyg": "Code Editors",
            r"(?i)form|valid": "Data Validation & Serialization",
            r"(?i)framework|mvc": "Frontend Frameworks",
            r"(?i)http|ajax|fetch": "HTTP Libraries",
            r"(?i)image|canvas": "Image Processing",
            r"(?i)logging|log.?manage|logger": "Logging & Diagnostics",
            r"(?i)map|geo": "Data Analysis",
            r"(?i)notification|toast": "Frontend Frameworks",
            r"(?i)package|npm": "Package Managers",
            r"(?i)promise|async": "Async & Concurrency",
            r"(?i)reactive|stream": "Real-time Communication",
            r"(?i)scroll|lazy": "Frontend Frameworks",
            r"(?i)storage|database": "Databases",
            r"(?i)template": "Template Engines",
            r"(?i)test": "Testing Frameworks",
            r"(?i)ui|component": "Frontend Frameworks",
        }
    ),
    (
        "ziadoz/awesome-php",
        "awesome-php",
        {
            r"(?i)auth": "Auth & Identity",
            r"(?i)cache": "Caching",
            r"(?i)cli|command|console": "CLI Frameworks",
            r"(?i)cms|content": "Content Management Systems",
            r"(?i)orm|persist|active.?record": "ORMs",
            r"(?i)driver|connector": "Database Drivers",
            r"(?i)migrat": "Database Migrations",
            r"(?i)database|sql": "Databases",
            r"(?i)date.?time|datetime|date.?util": "Date & Time",
            r"(?i)debug|profil": "Logging & Diagnostics",
            r"(?i)ci.?cd|continuous.?integr|deploy.?pipeline": "CI/CD Tools",
            r"(?i)email": "Email",
            r"(?i)file|filesystem": "File Managers",
            r"(?i)framework|micro": "Backend Frameworks",
            r"(?i)http.?client": "HTTP Libraries",
            r"(?i)image": "Image Processing",
            r"(?i)logging|log.?manage|logger": "Logging & Diagnostics",
            r"(?i)machine.?learn|ai": "AI/ML Libraries",
            r"(?i)queue|message|event": "Data Pipelines",
            r"(?i)search": "Search Engines",
            r"(?i)security|crypt": "Security Scanning",
            r"(?i)serial|json|xml": "Data Validation & Serialization",
            r"(?i)static.?analy": "Static Analysis",
            r"(?i)template": "Template Engines",
            r"(?i)test": "Testing Frameworks",
            r"(?i)valid": "Data Validation & Serialization",
            r"(?i)compress|archiv": "Compression & Archiving",
            r"(?i)config": "Configuration",
            r"(?i)text|string|regex": "Text Processing",
        }
    ),
    (
        "matteocrippa/awesome-swift",
        "awesome-swift",
        {
            r"(?i)animation": "iOS UI Components",
            r"(?i)auth": "Auth & Identity",
            r"(?i)bluetooth|iot": "Embedded & IoT",
            r"(?i)cache|database|realm|core.?data": "iOS Networking & Data",
            r"(?i)cli|command": "CLI Frameworks",
            r"(?i)date.?time|datetime|date.?util": "Date & Time",
            r"(?i)game": "Game Engines",
            r"(?i)html|xml|json|serial": "Data Validation & Serialization",
            r"(?i)http|network|api": "iOS Networking & Data",
            r"(?i)image|photo": "Image Processing",
            r"(?i)keyboard|input": "iOS UI Components",
            r"(?i)layout|ui|view": "iOS UI Components",
            r"(?i)logging|log.?manage|logger": "Logging & Diagnostics",
            r"(?i)machine.?learn|ai|core.?ml": "AI/ML Libraries",
            r"(?i)map|location": "iOS UI Components",
            r"(?i)notification|push": "iOS UI Components",
            r"(?i)pattern|architect": "Utilities",
            r"(?i)security|crypto|key": "Encryption & Privacy Tools",
            r"(?i)test": "Testing Frameworks",
            r"(?i)video|audio|media": "Media Players",
        }
    ),
    (
        "KotlinBy/awesome-kotlin",
        "awesome-kotlin",
        {
            r"(?i)android": "Android UI Components",
            r"(?i)build|gradle": "Build Tools",
            r"(?i)cli|command": "CLI Frameworks",
            r"(?i)orm|persist": "ORMs",
            r"(?i)driver|connector": "Database Drivers",
            r"(?i)database|sql": "Databases",
            r"(?i)http.?client": "HTTP Libraries",
            r"(?i)http|network|api": "Backend Frameworks",
            r"(?i)json|serial": "Data Validation & Serialization",
            r"(?i)logging|log.?manage|logger": "Logging & Diagnostics",
            r"(?i)test": "Testing Frameworks",
            r"(?i)web|framework": "Backend Frameworks",
        }
    ),
    (
        "sindresorhus/awesome-nodejs",
        "awesome-nodejs",
        {
            r"(?i)build|bundl|task": "Build Tools",
            r"(?i)cli|command|terminal": "CLI Frameworks",
            r"(?i)compress": "Compression & Archiving",
            r"(?i)control.?flow|promise|async": "Async & Concurrency",
            r"(?i)orm|active.?record|persist": "ORMs",
            r"(?i)driver|connector": "Database Drivers",
            r"(?i)migrat": "Database Migrations",
            r"(?i)cach|redis|memcache": "Caching",
            r"(?i)database|sql|mongo": "Databases",
            r"(?i)date.?time|datetime|date.?util": "Date & Time",
            r"(?i)debug|profil": "Logging & Diagnostics",
            r"(?i)email": "Email",
            r"(?i)file.?system|fs|path": "File Managers",
            r"(?i)http|request": "HTTP Libraries",
            r"(?i)image|graphics": "Image Processing",
            r"(?i)job.?queue|scheduling": "Data Pipelines",
            r"(?i)json|yaml|serial|valid": "Data Validation & Serialization",
            r"(?i)logging|log.?manage|logger": "Logging & Diagnostics",
            r"(?i)machine.?learn|ai": "AI/ML Libraries",
            r"(?i)monitor|process.?manage": "Monitoring & Metrics",
            r"(?i)network|socket|protocol": "Real-time Communication",
            r"(?i)package": "Package Managers",
            r"(?i)scraping|crawl|parse": "Web Scraping & Parsing",
            r"(?i)security|crypto|auth": "Security Scanning",
            r"(?i)stream|reactive": "Real-time Communication",
            r"(?i)template|view": "Template Engines",
            r"(?i)test": "Testing Frameworks",
            r"(?i)text|string|regex|natural": "Text Processing",
            r"(?i)web.?framework|express|koa": "Backend Frameworks",
            r"(?i)config": "Configuration",
        }
    ),
    # --- Additional awesome lists ---
    (
        "akullpp/awesome-java",
        "awesome-java",
        {
            r"(?i)build|deploy": "Build Tools",
            r"(?i)bytecode|compiler": "Programming Languages",
            r"(?i)cli|command": "CLI Frameworks",
            r"(?i)cluster|distribut": "Container Orchestration",
            r"(?i)config": "Configuration",
            r"(?i)constraint|logic": "Scientific Computing",
            r"(?i)csv|json|xml|serial|yaml": "Data Validation & Serialization",
            r"(?i)orm|persist|jpa": "ORMs",
            r"(?i)driver|connector|jdbc": "Database Drivers",
            r"(?i)migrat": "Database Migrations",
            r"(?i)cach|redis|memcache": "Caching",
            r"(?i)database|sql": "Databases",
            r"(?i)date.?time": "Date & Time",
            r"(?i)dependency.?inject": "Backend Frameworks",
            r"(?i)development.?tool|ide": "Code Editors",
            r"(?i)email": "Email",
            r"(?i)functional|reactive": "Async & Concurrency",
            r"(?i)game": "Game Engines",
            r"(?i)gui.?framework|gui.?toolkit|gui.?librar|desktop.?framework": "Desktop App Frameworks",
            r"(?i)blockchain|ethereum|web3|solidity": "Blockchain & Web3",
            r"(?i)natural.?lang|nlp": "NLP & Text AI",
            r"(?i)llm|openai|langchain|gpt": "LLM Tools",
            r"(?i)machine.?learn|deep.?learn|ai|neural": "AI/ML Libraries",
            r"(?i)http.?client": "HTTP Libraries",
            r"(?i)http|web.?framework|rest|servlet": "Backend Frameworks",
            r"(?i)image|pdf|document": "Image Processing",
            r"(?i)introspect|reflect": "Utilities",
            r"(?i)io|file|stream": "File Managers",
            r"(?i)job.?schedul|queue": "Data Pipelines",
            r"(?i)json": "Data Validation & Serialization",
            r"(?i)logging|log.?manage|logger": "Logging & Diagnostics",
            r"(?i)messag|event|jms": "Data Pipelines",
            r"(?i)micro": "Backend Frameworks",
            r"(?i)monitor|metric|performance": "Monitoring & Metrics",
            r"(?i)text|string": "Text Processing",
            r"(?i)network|socket|protocol": "Networking",
            r"(?i)platform|util": "Utilities",
            r"(?i)process|thread|concurr": "Async & Concurrency",
            r"(?i)science|math|numer": "Scientific Computing",
            r"(?i)search": "Search Engines",
            r"(?i)security|crypto|auth": "Security Scanning",
            r"(?i)static.?analy": "Static Analysis",
            r"(?i)template|render": "Template Engines",
            r"(?i)test": "Testing Frameworks",
            r"(?i)valid": "Data Validation & Serialization",
            r"(?i)compress|archiv": "Compression & Archiving",
        }
    ),
    (
        "Awesome-Windows/Awesome",
        "awesome-windows",
        {
            r"(?i)audio": "Music Production",
            r"(?i)backup": "Backup & Sync",
            r"(?i)chat|messag": "Communication",
            r"(?i)compress|archiv": "Compression & Archiving",
            r"(?i)customiz|personaliz": "Window Managers",
            r"(?i)data.?recover": "Backup & Sync",
            r"(?i)develop|program|ide|text.?editor": "Code Editors",
            r"(?i)document|office": "Office Suites",
            r"(?i)download|torrent": "Torrent Clients",
            r"(?i)email": "Email",
            r"(?i)game": "Game Engines",
            r"(?i)graphic|image|photo": "Image Editors",
            r"(?i)online.?storage|cloud.?storage": "Cloud Storage",
            r"(?i)productiv": "Launcher & Productivity Utils",
            r"(?i)proxy|vpn": "VPN",
            r"(?i)security|password|privacy": "Password Managers",
            r"(?i)terminal|console": "Terminal Emulators",
            r"(?i)text.?editor": "Code Editors",
            r"(?i)utilit|system": "System Utilities",
            r"(?i)video": "Video Editing",
            r"(?i)web.?browser": "Browsers",
        }
    ),
    (
        "wasabeef/awesome-android-ui",
        "awesome-android-ui",
        {
            r".*": "Android UI Components",
        }
    ),
    (
        "vsouza/awesome-ios",
        "awesome-ios",
        {
            r"(?i)animation": "iOS UI Components",
            r"(?i)auth": "Auth & Identity",
            r"(?i)cache|database|realm|core.?data": "iOS Networking & Data",
            r"(?i)chart|graph|visual": "iOS UI Components",
            r"(?i)chat|messag": "Communication",
            r"(?i)date.?time|datetime|date.?util": "Date & Time",
            r"(?i)file|document": "File Managers",
            r"(?i)game": "Game Engines",
            r"(?i)http|network|api": "iOS Networking & Data",
            r"(?i)image|photo|camera": "Image Processing",
            r"(?i)json|serial|parse": "Data Validation & Serialization",
            r"(?i)keyboard|input": "iOS UI Components",
            r"(?i)layout|ui|view|table|collection": "iOS UI Components",
            r"(?i)location|map|gps": "iOS UI Components",
            r"(?i)logging|log.?manage|logger": "Logging & Diagnostics",
            r"(?i)machine.?learn|ai|core.?ml|vision": "AI/ML Libraries",
            r"(?i)media|audio|video|player": "Media Players",
            r"(?i)notification|push": "iOS UI Components",
            r"(?i)security|crypto|key": "Encryption & Privacy Tools",
            r"(?i)test": "Testing Frameworks",
            r"(?i)text|label|font": "Fonts & Typography",
            r"(?i)websocket|socket|realtime": "Real-time Communication",
        }
    ),
    (
        "veggiemonk/awesome-docker",
        "awesome-docker",
        {
            r"(?i)ci.?cd|continuous.?integr|registry": "CI/CD Tools",
            r"(?i)monitor|log|metric": "Monitoring & Metrics",
            r"(?i)network|proxy|load.?bal": "Networking",
            r"(?i)orchestrat|deploy|swarm": "Container Orchestration",
            r"(?i)secur|scan|audit": "Security Scanning",
            r"(?i)storage|volume|backup": "Backup & Sync",
            r"(?i)terminal|cli": "CLI Frameworks",
            r"(?i)test": "Testing Frameworks",
            r"(?i)tool|util|manage": "Container Orchestration",
        }
    ),
    (
        "ramitsurana/awesome-kubernetes",
        "awesome-kubernetes",
        {
            r"(?i)ci.?cd|continuous.?integr|deploy.?pipeline": "CI/CD Tools",
            r"(?i)monitor|log|metric|observ": "Monitoring & Metrics",
            r"(?i)network|mesh|ingress|proxy": "Networking",
            r"(?i)package|helm|chart": "Package Managers",
            r"(?i)secur|policy|rbac": "Security Scanning",
            r"(?i)storage|volume|persist": "Backup & Sync",
            r"(?i)tool|util|manage|dashboard": "Container Orchestration",
        }
    ),
    (
        "iCHAIT/awesome-macOS",
        "awesome-macOS",
        {
            r"(?i)audio|music": "Music Production",
            r"(?i)backup": "Backup & Sync",
            r"(?i)browser": "Browsers",
            r"(?i)chat|messag|social": "Communication",
            r"(?i)develop|ide|text.?editor": "Code Editors",
            r"(?i)download": "Torrent Clients",
            r"(?i)email": "Email",
            r"(?i)file|finder": "File Managers",
            r"(?i)game": "Game Engines",
            r"(?i)graphic|image|photo": "Image Editors",
            r"(?i)note|writing": "Note Taking",
            r"(?i)productiv|util": "Launcher & Productivity Utils",
            r"(?i)security|password|privacy|vpn": "Password Managers",
            r"(?i)terminal|shell": "Terminal Emulators",
            r"(?i)video": "Video Editing",
            r"(?i)window.?manage": "Window Managers",
        }
    ),
    (
        "analysis-tools-dev/static-analysis",
        "awesome-static-analysis",
        {
            r"(?i)lint": "Linters",
            r"(?i)format": "Formatters",
            r"(?i)security|vulnerab|sast": "Security Scanning",
            r"(?i)binary|decompil|disassembl": "Security Scanning",
            r".*": "Static Analysis",
        }
    ),
    (
        "mfornos/awesome-microservices",
        "awesome-microservices",
        {
            r"(?i)api.?gateway|proxy": "API Clients",
            r"(?i)config|service.?discover": "Infrastructure as Code",
            r"(?i)container|docker|kubernetes": "Container Orchestration",
            r"(?i)messag|event|queue|stream": "Data Pipelines",
            r"(?i)monitor|log|trace|metric": "Monitoring & Metrics",
            r"(?i)platform|framework": "Backend Frameworks",
            r"(?i)secur|auth": "Auth & Identity",
            r"(?i)serial|protocol|rpc|grpc": "Backend Frameworks",
            r"(?i)test": "Testing Frameworks",
        }
    ),
]


def get_section_category(section_name, section_map):
    """Match a section name against the regex patterns in a section map."""
    import re
    for pattern, category in section_map.items():
        if re.search(pattern, section_name):
            return category
    return None
